### ISSUE TITLE
debugging

### ISSUE THREAD

**Issue by jy634** [shendurelab/fly-atac#3]
Hi, I was trying to implement this pipeline with my sci-ATAC data, and I just wanted to note down couple of typos and issues with following the pipeline in the codes:

1. "sc_atac_window_counter.py" doesn't contain "writebinary" option in the _counter_ function. 
2. "sc_atac_bam2matrix.py" has inconsistent argument calls throughout the code.
3. I don't know why, but "scriptdir" doesn't include "/" at the end, and it throws an error.
4. Can you include in the dependencies that this uses python2? (print function wouldn't work with python3) 
5. As mentioned in the earlier open issue, can you tell us what format the INDEX TABLE is supposed to be in? I see from the code that it's a file with two columns, but there's no way of figuring out whether I need the i5/i7/r5/r7 primer list or the full combination of the indices. Would you be able to provide a sample index table? 
6. What doesn NoTags mean?

Thank you!

**Comment by cusanovich** [comment]
Thanks for your notes. And sorry for the confusion. I believe I've got all of these addressed now.

1. Removed "writebinary" (a holdover from a previous version of the script).
2. I believe I've gotten all of these fixed now.
3. Added slashes.
4. Added a note to the README that this is Python2.
5. Added index tables to the repository and also tried to explain them better in the README.
6. "NoTags" was another holdover from a previous script. I've removed it now.

Thanks again for your comments.
