### ISSUE TITLE
Fix Barcodes Part

### ISSUE THREAD

**Issue by marvinquiet** [shendurelab/fly-atac#4]
I don't know why I still could not get the correct index conversion table in the journal _multiplex Single Cell Profiling of Chromatin Accessibility by Combinatorial Cellular Indexing_. It seems these two papers use the same protocol and edit distance rule.

**Comment by cusanovich** [comment]
Responding too late to be of much help to you (sorry!), but there would have been some differences in the barcode correction script between the two papers, so there are likely to be some small differences between the two. Nonetheless, we provide index information with the GEO records for both (GSE68103 and GSE101581).
