### ISSUE TITLE
IOError: [Errno 5] Input/output error

### ISSUE THREAD

**Issue by tAndreani** [shendurelab/fly-atac#5]
Hello,  
I am running the first part of the pipeline as described in the ReadMe:  

python sc_atac_fastq2bam.py -R1 SRR5837698_1.fastq.gz -R2 SRR5837698_2.fastq.gz -O pre.processing -P scATAC.Reproduce -G /path/to/the/genome/

The script is running and the trimming of the reads is ongoing, hence everything seems fine. But, looking at the initial output I am having this issue:    

```
Fixing barcodes...
Traceback (most recent call last):
  File "/data/PROJECTS/Datasets/sci-ATAC-seq_fly/sra/sc_atac_10bpbarcode_split.py", line 127, in <module>
    outfasta1.writelines(reads1)
IOError: [Errno 5] Input/output error
Trimming adapters...
```  

As I said the script is still running and the log files from trimmomatic look fine at the moment without any error. Have you experienced anything similar?

**Comment by cusanovich** [comment]
I haven't run into this. Did you end up with two trimmed fastq files anyway?

**Comment by tAndreani** [comment]
Yes thanks, I figure it out the problem. It was within our server and I fixed it.
