### ISSUE TITLE
cell barcode issue

### ISSUE THREAD

**Issue by jphe** [shendurelab/fly-atac#6]
Hi,

I have download the SRA file from GEO (https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE111586), and convert it to fastq with fastq-dump. Seems it just like typical fastq file, I can not find where the barcode is. 

less SRR6819235.2_1.fastq.gz
@SRR6819235.2.1 D00584:151:C9KLUANXX:1:1108:1100:1964 length=50
NTTTTGTTCCCCTTTCTAAGAAGGATCGAAGTATCCACACTTTGGCCTTC
+SRR6819235.2.1 D00584:151:C9KLUANXX:1:1108:1100:1964 length=50
#<<<<FFFFFFFFFFFFFFFFFBFFFFFF//<FFFBFFFFFFFBFFFF<F
@SRR6819235.2.2 D00584:151:C9KLUANXX:1:1108:1494:1991 length=50
CACATGAACTGGGACTACTTCCTGCTAAGAGAAAGCAGCCAGACATTTAT
+SRR6819235.2.2 D00584:151:C9KLUANXX:1:1108:1494:1991 length=50
BBBBBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFFFFFFFFFFFFFF/
 less SRR6819235.2_2.fastq.gz
@SRR6819235.2.1 D00584:151:C9KLUANXX:1:1108:1100:1964 length=50
GAGCTCTGGAGATACTTGTTAGNNNNNNTTGTTTNNNNNNNNNNNNNNNN
+SRR6819235.2.1 D00584:151:C9KLUANXX:1:1108:1100:1964 length=50
B<<B////FFB<F/////BFFF######<</<F/################
@SRR6819235.2.2 D00584:151:C9KLUANXX:1:1108:1494:1991 length=50
GTTCTCAGCAACCTCTACTTCCCCTCCCTTTGCCTTTGGTAGAATTTCTT
+SRR6819235.2.2 D00584:151:C9KLUANXX:1:1108:1494:1991 length=50
BBBBBFFBF/FFF//</<<FFFBF/BF</<F/B<FFBBFFFFF/<<B/7<

Thanks,
Jphe

**Comment by cusanovich** [comment]
Apologies for not responding sooner. The barcodes should be available from SRA Toolkit if you use the -F argument with the fastq-dump command.
